## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7.0-alpha.0
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
 allow_failures:
 - julia: nightly

after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # Documentation
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'include(joinpath("docs", "make.jl"))'
