authors = ["José Bayoán Santiago Calderón <naoyabpr@gmail.com>"]
license = "MIT"
repository = "https://github.com/Nosferican/NCEI.jl.git"
description = "Interface for the National Centers for Environmental Information (NCEI) API"
keywords = ["API", "Interface", "NOAA", "Weather", "Climate", "Data", "NCEI"]
name = "NCEI"
uuid = "1f554e9c-ddc6-5d78-a4ef-ff7defcf835d"
version = "1.0.3"

[compat]
julia = "0.7"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
LazyJSON = "fc18253b-5e1b-504c-a4a2-9ece4944c004"
