desc = "Interface for the National Centers for Environmental Information (NCEI) API services."
keywords = ["NOAA", "NCEI", "Climate", "Weather", "API"]
license = "MIT"
name = "NCEI"
uuid = "15ccf62c-2fb9-11e8-2290-0516c70b7bac"
version = "0.1.0"
author = ["José Bayoán Santiago Calderón"]
email = ["naoyabpr@gmail.com"]
page = [""]

[deps]
HTTP
LazyJSON
DataFrames
